baseurl = "http://boxturtle.x:8180/"
languageCode = "en-us"
title = "Boxturtle Demo Web Site"

[[menu.main]]
    name = "Home"
    weight = -999
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "News"
    weight = 0
    identifier = "post"
    url = "/post/"

[[menu.main]]
    name = "Tags"
    weight = 9999
    identifier = "tags"
    url = "/tags/"
